# Generated by Django 5.2.12 on 2026-03-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Apointment',
        ),
    ]
