# Generated by Django 5.2.12 on 2026-03-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_appointment_apointment'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apointment',
            new_name='Appointment',
        ),
    ]
