# Generated by Django 5.2.12 on 2026-03-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalNote',
        ),
    ]
